config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :posts do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image

  validates :image, presence: true

  def self.search(search)
    return Post.all unless search
    Post.where(['title LIKE(?)',"%#{search}"])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment:profile_image
  has_many :posts

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @posts = Post.search(params[:search]).limit(132)
    @search = params[:search]
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to users_path
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private
  def post_params
    params.require(:post).permit(:title,:text,:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:profile,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="home-wrapper">
  <div class="back-image">
    <h1 class="home-title">MotoUp</h1>
  </div>
  <div class="week-fav bound">
    <h2>今週のおすすめ選手</h2>
    <div class="fav-img">
      <%# <img src="assets/F1VER.webp"> %>
      <%# <img src="assets/VER.jpeg"> %>
      <%# <img src="assets/no-image.png"> %>
      <%= image_tag asset_path("F1VER.webp", alt: "お気に入り画像1") %>
      <%= image_tag asset_path("no-image.png", alt: "お気に入り画像2") %>
      <%# <%= image_tag asset_path("no-image.png", alt: "お気に入り画像") %>
    </div>
    <ul class="fav-date">
      <li class="name">
        マックス・フェルスタッペン
      </li>
      <li class="text">
        レッドブルレーシングからF1へ参戦しているドライバー
        2020年7月時点でポイントランキングで3位。まだ、22歳と若く今年は最年少F1チャンピオンに期待がかかる。
      </li>
      <li class="team">
        <h4>所属チーム👇</h4>
        アストンマーティン・レッドブルレーシング
      </li>
      <li class="team-text">
        イギリスに本拠地を置く。F1トップチーム。
        今年は、フェルスタッペン＆アルボン選手で参戦中。
        ドライバー・コンストラクターズタイトルをそれぞれ4度獲得している。
      </li>
    </ul>
  </div>
</section>

<div class="app-Ex">
  <h2>このアプリについて</h2>
  <div class="Ex-text">
    このアプリは、モータースポーツ専用の写真UPアプリになります。
    <br>
    投稿一覧から投稿された写真の閲覧が可能です。投稿を行いたい場合には、
    <span>
      <%= link_to "こちら", new_user_registration_path %>
    </span>
    からサインアップすることで投稿可能になります。
  </div>
</div>

<footer>
  <div class="cmark">©fmsapp<div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MotoUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar is-black">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-3 has-text-warning" style="font-family: HoeflerText-Black;">Moto Up</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in?%>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-start">
            <p class="navbar-item">
                <%= link_to "投稿一覧",posts_path,class:"button is-link"%>
            </p>
            <p class="navbar-item">
                <%= link_to "投稿",new_post_path,class:"button is-link" %>
            </p>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "マイページ",user_path(current_user),class:"button is-link" %>
                <p class="control">
                <%= link_to "ユーザー一覧",users_path,class:"button is-link"%>
                </p>
                <p class="control">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-link"%>
                </p>
              </div>
            </div>
          </div>
        </div>
      <%else%>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "投稿一覧",posts_path,class:"button is-link"%>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ユーザー一覧",users_path,class:"button is-link"%>
                </p>
                <p class="control">
                  <%= link_to "Login", new_user_session_path, class: "button  is-link " %>
                </p>
                <p class="control">
                  <%= link_to "Sign_up", new_user_registration_path, class: "button is-link "%>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </nav>  
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<section class="header-posts">
  <h1 class="title">投稿編集画面</h1>
<section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @post do |f|%>

          <%= f.label :title,class:"label" %>
          <%= f.text_field :title, class:"input"%>

          <%= f.label :text,class:"label" %>
          <%= f.text_field :text, class:"textarea"%>

          <%= f.label :image,class:"label" %>
          <%= f.attachment_field :image, class:"input" %>

          <%= f.submit "更新", class:"button is-link"%>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="header-posts">
  <h1>投稿一覧</h1>
  <div class="searchbox">
    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "キーワード入力", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
</section>


<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @posts.each do |post| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <%= attachment_image_tag post, :image %>
                <%end%>
              <figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <figure class="image is-64x64">
                    <%= attachment_image_tag post.user, :profile_image,fallback:"no-image.png",class:"is-rounded" %>
                  </figure>
                </div>
                <div class="content">
                  <p class="title is-4">
                    <%= link_to user_path(post.user.id) do %>
                      <%= post.user.username %>
                    <% end %>
                  </p>
                </div>
              </div>
              <div class="content">
                <%= post.title %>
              </div>
              <%= post.created_at.strftime("%Y-%m-%d %H:%M") %> 投稿
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<section class="header-posts">
  <h1 class="post-title">投稿画面</h1>
<section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%=form_for @post do |f| %>

          <%= f.label :title,class:"label" %>
          <%= f.text_field :title,class:"input" %>


          <%= f.label :text,class:"label" %>
          <%= f.text_area :text,class:"textarea"%>

          <%= f.label :image,class:"label"%>
          <%= f.attachment_field :image,class:"input"%>

          <%= f.submit "投稿", class:"button is-link"%>

        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/search.html.erb
<section class="header-posts">
  <h1>検索結果一覧</h1>
</section>


<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @posts.each do |post| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <%= attachment_image_tag post, :image %>
                <%end%>
              <figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <figure class="image is-64x64">
                    <%= attachment_image_tag post.user, :profile_image,fallback:"no-image.png",class:"is-rounded" %>
                  </figure>
                </div>
                <div class="content">
                  <p class="title is-4">
                    <%= link_to user_path(post.user.id) do %>
                      <%= post.user.username %>
                    <% end %>
                  </p>
                </div>
              </div>
              <div class="content">
                <%= post.title %>
              </div>
              <%= post.created_at.strftime("%Y-%m-%d %H:%M") %> 投稿
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<h1 class="post-showtitle">投稿詳細ページ</h1>

<section class="show-content">
  <div class="show-wrapper">
    <%= attachment_image_tag @post, :image,class:"example" %>
    <div class="right-box">
      <div class="show-name">ユーザーネーム:
      <br>
        <%=link_to user_path(@post.user.id) do %>
          <%= @post.user.username %>
        <% end %>
      </div>
      <div class="show-title">
      タイトル:
      <br> 
      <%= @post.title %>
      </div>
      <div class="show-text">
        テキスト:
        <br>
        <%= simple_format @post.text %>
      </div>
    </div>
  </div>


  <% if user_signed_in? && @post.user.id == current_user.id %>
    <%= link_to "編集",edit_post_path(@post), class:"button is-link"%>
  <%end%>
</section>

app/views/users/edit.html.erb
<header class="header">
  <h1 class="edit-title">プロフィール編集画面</h1>
</header>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>

          <%=f.label :username,class:"label" %>
          <%= f.text_field :username,class:"input" %>

          <%=f.label :email,class:"label" %>
          <%= f.text_field :email,class:"input" %>

          <%=f.label :profile,class:"label" %>
          <%= f.text_area :profile,class:"textarea" %>

          <%=f.label :profile_image,class:"label"%>
          <%= f.attachment_field :profile_image,class:"input" %>

          <%=f.submit "更新",class:"button is-link"%>

        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
      <h1 class="title">ユーザー一覧</h1>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image is-4by3">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="username"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<header>
  <h1 class="profile-title">プロフィール</h1>
</header>
<section class="pf-wrapper">
  <div class="pf-image">
    <div class="pf-img">
      <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png" %>
    </div>
      <div class="namebox">
        <%= @user.username%>
      <div class="profilebox">
        <%= @user.profile %>
      </div>
      </div>
      <div class="emailbox">
        <% if user_signed_in? && @user.id == current_user.id %>
          <%= @user.email%>
          <%= link_to "編集", edit_user_path(@user), class:"button is-link"%>
        <% end %>
      </div>
    </div>
</section>

<h1 class="mypost-title"><%= @user.username%>さんの投稿</h1>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.posts.each do |post| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <%= attachment_image_tag post, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to"投稿詳細", post_path(post), class: "button is-link"  %>
                  <% if user_signed_in? && @user.id == current_user.id %>
                    <%= link_to "投稿削除",post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "button is-link" %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <%= post.created_at.strftime("%Y-%m-%d %H:%M") %> 投稿
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>